Repository GSG-G9/calorie-tracker, pull requests merged in 2021-02, with the labels that each got.

#21 README
  README.md
Labels: Read-Me

#27 file structure
  .eslintrc.js
  .gitignore
  .travis.yml
  client/.eslintcache
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  package-lock.json
  package.json
  server/__test__/index.test.js
  server/app.js
  server/controllers/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/index.js
  server/database/queries/index.js
  server/index.js
  server/middlewares/auth/index.js
  server/middlewares/errorHandle/index.js
  server/middlewares/index.js
  server/routes.js
  server/utils/index.js
  server/utils/validation/index.js
Labels: Awaiting Review, Back-end, File-Structure, FrontEnd

#55 Eslint and VsCode Configration
  .eslintrc.js
  .eslintrc.json
  .vscode/settings.json
  client/.eslintcache
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.js
  package-lock.json
  package.json
Labels: Awaiting Review

#56 Travis file modified
  .gitignore
  .travis.yml
  .vscode/settings.json
  README.md
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  package-lock.json
  server/__test__/index.test.js
Labels: Awaiting Review

#66 README
  README.md
  client/src/App.js
  client/src/index.js
Labels: Awaiting Review, Read-Me

#54 initial server created
  .gitignore
  client/.eslintcache
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  package-lock.json
  package.json
  server/app.js
  server/index.js
  server/router.js
  server/routes.js
Labels: Done, File-Structure, npm module

#63 Database schema
  server/database/config/build.sql
Labels: Back-end, Done

#57 Create Initial Database
  client/package-lock.json
  client/package.json
  config.env
  package-lock.json
  server/database/config/build.js
  server/database/config/connection.js
  server/database/config/index.js
Labels: Awaiting Review

#75 added fake data of the exercises
  server/database/config/fakeData.sql
Labels: Awaiting Review

#83 created textFeild component
  client/package-lock.json
  client/package.json
  client/src/components/input/InputFeild.js
Labels: Awaiting Review

#76 created button component
  .vscode/settings.json
  client/package-lock.json
  client/src/component/Button/index.js
Labels: Awaiting Review

#72 Doughnut Chart Component
  client/.eslintcache
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Button/index.js
  client/src/components/DoughnutChart/index.js
  client/src/components/DoughnutChart/style.css
  client/src/components/InputFeild/index.js
  package-lock.json
  package.json
Labels: Awaiting Review

#74 added food fake data
  config.env
  package-lock.json
  server/database/config/build.sql
  server/database/config/fakeData.sql
Labels: Done

#85 card component
  client/package-lock.json
  client/src/components/Card/index.js
  client/src/components/Card/style.css
Labels: Done

#78 Creating Container component
  client/package-lock.json
  client/src/components/Container/index.js
Labels: Done

#87 86 handle error
  package-lock.json
  package.json
  server/app.js
  server/middlewares/errorHandle/index.js
  server/middlewares/index.js
  server/router.js
Labels: Awaiting Review

#95 install pre-commit
  client/package.json
  package-lock.json
  package.json
  server/__test__/index.test.js
  server/app.js
  server/database/config/build.js
  server/database/config/connection.js
  server/database/config/index.js
  server/index.js
  server/middlewares/errorHandle/index.js
  server/middlewares/index.js
  server/router.js
Labels: Done

#91 sign up route
  .gitignore
  .travis.yml
  .vscode/settings.json
  package-lock.json
  package.json
  server/__test__/database/auth.test.js
  server/__test__/index.test.js
  server/__test__/routes/auth.test.js
  server/app.js
  server/controllers/index.js
  server/controllers/signup.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/getEmail.js
  server/database/queries/getUserActivity.js
  server/database/queries/signup.js
  server/middlewares/errorHandle/index.js
  server/router.js
  server/utils/dailyCalories.js
  server/utils/validation/index.js
  server/utils/validation/signupSchema.js
Labels: Done

#88 41 login back
  client/.gitignore
  package-lock.json
  package.json
  server/__test__/database/auth.test.js
  server/__test__/routes/auth.test.js
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/signup.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/index.js
  server/database/queries/index.js
  server/middlewares/errorHandle/index.js
  server/router.js
  server/utils/index.js
  server/utils/signToken.js
  server/utils/validation/index.js
  server/utils/validation/loginSchema.js
Labels: Approved, Done

#93 Create Theme Provider
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/src/App.js
  client/src/components/ThemeProvider/index.js
  package-lock.json
  package.json
  server/__test__/routes/auth.test.js
Labels: Done

#97 GET /api/v1/healthnews
  package.json
  server/__test__/database/index.test.js
  server/__test__/routes/auth.test.js
  server/controllers/healthNews.js
  server/controllers/index.js
  server/database/config/fakeData.sql
  server/database/queries/getNews.js
  server/database/queries/index.js
  server/router.js
Labels: Awaiting Review

#81 loading progress bar component
  client/src/components/Loading/index.js
  server/__test__/auth.test.js
  server/__test__/database/auth.test.js
  server/__test__/database/index.test.js
  server/database/config/fakeData.sql
Labels: Done

#103 react router
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App/index.js
  client/src/App/style.css
  client/src/Pages/Calories/index.js
  client/src/Pages/Exercise/index.js
  client/src/Pages/Food/index.js
  client/src/Pages/Home/index.js
  client/src/Pages/Login/index.js
  client/src/Pages/Logout/index.js
  client/src/Pages/MyFood/index.js
  client/src/Pages/Nutrition/index.js
  client/src/Pages/Profile/index.js
  client/src/Pages/Signup/index.js
  client/src/Utils/constant.js
  server/__test__/index.test.js
Labels: Awaiting Review

#102 Verify Token
  server/controllers/login.js
  server/middlewares/auth/index.js
  server/middlewares/index.js
  server/router.js
  server/utils/index.js
  server/utils/jwt.js
  server/utils/signToken.js
Labels: Done

#89 GET /api/v1/food
  package-lock.json
  package.json
  server/__test__/index.test.js
  server/controllers/getFood/index.js
  server/controllers/index.js
  server/database/config/connection.js
  server/database/queries/getFood/index.js
  server/database/queries/index.js
  server/router.js
Labels: Done

#101 Create User Provider Context
  client/package-lock.json
  client/src/components/userProvider/index.js
Labels: Done

#107 food category back
  server/__test__/index.test.js
  server/controllers/foodCategory.js
  server/controllers/index.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/queries/getFoodCategory.js
  server/database/queries/index.js
  server/router.js
Labels: Done

#92 GET calories route
  .vscode/settings.json
  client/.eslintrc.json
  client/public/manifest.json
  client/src/App/style.css
  client/src/Pages/Calories/index.js
  client/src/Pages/Exercise/index.js
  client/src/Pages/Food/index.js
  client/src/Pages/Home/index.js
  client/src/Pages/Login/index.js
  client/src/Pages/Logout/index.js
  client/src/Pages/MyFood/index.js
  client/src/Pages/Nutrition/index.js
  client/src/Pages/Profile/index.js
  client/src/Pages/Signup/index.js
  client/src/components/Card/index.js
  client/src/index.css
  package-lock.json
  package.json
  server/__test__/index.test.js
  server/controllers/getUserCalories/index.js
  server/controllers/index.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/config/index.js
  server/database/queries/calculateUserExercisesCalories/index.js
  server/database/queries/calculateUserFoodCalories/index.js
  server/database/queries/getUserCalories/index.js
  server/database/queries/index.js
  server/router.js
Labels: Done

#106 Create SignUp component
  client/package-lock.json
  client/package.json
  client/public/signupImages/1.png
  client/public/signupImages/2.png
  client/public/signupImages/3.png
  client/src/App/index.js
  client/src/Pages/Signup/index.js
  client/src/Utils/checkValidationPureFunction.js
  client/src/Utils/signUpBasicInfoValidation.js
  client/src/Utils/signUpPhysicalCharacteristicsValidation.js
  client/src/components/Alert/index.js
  client/src/components/Button/index.js
  client/src/components/Container/index.js
  client/src/components/InputField/index.js
  client/src/components/Loading/index.js
  client/src/components/Select/index.js
  client/src/components/SignupFormSteps/index.js
  client/src/components/StepContent/index.js
  client/src/components/ThemeProvider/index.js
  client/src/components/signUpForm/BasicUserInfo/index.js
  client/src/components/signUpForm/GenderSelection/index.js
  client/src/components/signUpForm/PhysicalCharacteristics/index.js
  server/app.js
  server/controllers/signup.js
Labels: Done

#108 Create Login Component
  client/package-lock.json
  client/src/Pages/Login/index.js
  client/src/Utils/validationLogin.js
  client/src/components/Button/index.js
  client/src/components/InputField/index.js
  client/src/components/Login/index.js
  package.json
  server/__test__/index.test.js
  server/controllers/login.js
  server/utils/validation/loginSchema.js
  server/utils/validation/signupSchema.js
Labels: Done

#90 POST api/v1/category/:categoryId/food/:foodId
  server/__test__/index.test.js
  server/controllers/getUserCalories/index.js
  server/controllers/index.js
  server/controllers/insertFood/index.js
  server/database/config/fakeData.sql
  server/database/queries/calculateUserExercisesCalories/index.js
  server/database/queries/index.js
  server/database/queries/insertFoodQuery.js
  server/router.js
  server/utils/index.js
  server/utils/validation/index.js
  server/utils/validation/insertFood.js
Labels: Done

#113 Create food categories component
  client/package-lock.json
  client/public/foodCategory/logo512.png
  client/public/index.html
  client/src/Pages/Food/index.js
  client/src/components/Container/index.js
  client/src/components/Loading/index.js
  client/src/components/SignupFormSteps/index.js
  client/src/components/StepContent/index.js
  client/src/components/food/CustomErrorMessage/index.js
  client/src/components/food/FoodCategories/index.js
  client/src/components/food/FoodCategoryButton/index.js
  client/src/components/food/FoodItem/index.js
  client/src/components/food/FoodItems/index.js
  client/src/components/food/FoodItemsSelected/index.js
  client/src/components/signUpForm/PhysicalCharacteristics/index.js
  client/src/index.css
  package-lock.json
  package.json
  server/app.js
  server/controllers/foodCategory.js
  server/database/config/fakeData.sql
Labels: Done

#105 NavBar and Popover components
  client/src/App/index.js
  client/src/Pages/Calories/index.js
  client/src/Pages/Exercise/index.js
  client/src/Pages/Home/index.js
  client/src/Pages/Logout/index.js
  client/src/Pages/MyFood/index.js
  client/src/Pages/Nutrition/index.js
  client/src/Pages/Profile/index.js
  client/src/components/AddFoodIcon/index.js
  client/src/components/NavBar/index.js
  client/src/components/NavBar/style.js
  client/src/components/Popover/index.js
  client/src/components/Popover/style.js
Labels: Done

#116 Daily User Calories
  client/src/components/CircularProgress/index.js
  client/src/components/DailyCaloriesCard/index.js
  client/src/components/DailyUserCalories/index.js
  client/src/components/DoughnutChart/index.js
Labels: Done

#110 food page front
  client/package-lock.json
  client/src/App/index.js
  client/src/Pages/FoodList/index.js
  client/src/Utils/constant.js
  client/src/components/Container/index.js
  client/src/components/FoodList/AllFoodList.js
  client/src/components/food/FoodCategories/index.js
  client/src/components/food/FoodItems/index.js
  client/src/components/food/FoodItemsSelected/index.js
  package-lock.json
  package.json
  server/__test__/index.test.js
  server/database/config/fakeData.sql
  server/database/queries/getFood/index.js
  server/database/queries/getFoodCategory.js
Labels: Done

#117 GET api/v1/profile
  server/__test__/index.test.js
  server/controllers/getProfile/index.js
  server/controllers/index.js
  server/database/config/build.sql
  server/database/queries/getProfile/index.js
  server/database/queries/index.js
  server/router.js
Labels: Done

#119 Food Quantity Component
  client/package-lock.json
  client/src/App/index.js
  client/src/Utils/filterNutrition.js
  client/src/components/DoughnutChart/index.js
  client/src/components/StepContent/index.js
  client/src/components/food/AddFoodQuantityButtons/index.js
  client/src/components/food/CustomErrorMessage/index.js
  client/src/components/food/FoodCategories/index.js
  client/src/components/food/FoodItem/index.js
  client/src/components/food/FoodItems/index.js
  client/src/components/food/FoodItemsSelected/index.js
  client/src/components/food/FoodQuantity/index.js
  client/src/components/food/FoodQuantity/style.js
  client/src/components/food/NutritionTable/index.js
  client/src/components/food/NutritionTable/style.js
  package-lock.json
  package.json
  server/controllers/getFoodById/index.js
  server/controllers/index.js
  server/database/queries/getFoodById/index.js
  server/database/queries/index.js
  server/router.js
Labels: Done

#123 edit food route
  server/controllers/editFood.js
  server/controllers/index.js
  server/database/queries/editFoodGrams.js
  server/database/queries/index.js
  server/router.js
  server/utils/index.js
  server/utils/validation/index.js
  server/utils/validation/validateFoodAmount.js
Labels: Done

#124 delete food route
  server/controllers/deleteFood.js
  server/controllers/editFood.js
  server/controllers/index.js
  server/database/config/build.sql
  server/database/queries/deleteFood.js
  server/database/queries/editFoodGrams.js
  server/database/queries/index.js
  server/router.js
Labels: Done

#114 home page
  client/package-lock.json
  client/src/App/index.js
  client/src/App/style.css
  client/src/Pages/Home/index.js
  client/src/components/DesktopNavBar/index.js
  client/src/components/DesktopNavBar/style.js
  client/src/components/Footer/index.js
  client/src/components/Home/index.js
  client/src/components/Home/style.js
  client/src/components/LoginSignupButtonsBox/index.js
  client/src/components/LoginSignupButtonsBox/style.js
  client/src/images/favicon.ico
  client/src/images/header.png
  client/src/images/sport.png
  server/app.js
Labels: Done

#121 GET /logout route
  server/__test__/index.test.js
  server/app.js
  server/controllers/index.js
  server/controllers/logout/index.js
  server/router.js
Labels: Done

#125 Profile page
  client/src/Pages/Profile/index.js
  client/src/components/Card/index.js
  client/src/components/Profile/index.js
Labels: Done

#122 Front End Protected Routes
  client/package-lock.json
  client/src/App/index.js
  client/src/Pages/FoodQuantity/index.js
  client/src/Pages/Logout/index.js
  client/src/Pages/index.js
  client/src/Utils/constant.js
  client/src/components/Alert/index.js
  client/src/components/Container/index.js
  client/src/components/DesktopNavBar/favicon.ico
  client/src/components/DesktopNavBar/index.js
  client/src/components/DesktopNavBar/style.js
  client/src/components/FoodList/AllFoodList.js
  client/src/components/Home/1.png
  client/src/components/Home/2.png
  client/src/components/Home/index.js
  client/src/components/Login/index.js
  client/src/components/LoginSignupButtonsBox/style.js
  client/src/components/Popover/index.js
  client/src/components/Popover/style.js
  client/src/components/SignupFormSteps/index.js
  client/src/components/food/FoodCategories/index.js
  client/src/components/food/FoodQuantity/style.js
  client/src/components/food/NutritionTable/index.js
  client/src/components/logout/index.js
  client/src/components/signUpForm/BasicUserInfo/index.js
  client/src/components/signUpForm/GenderSelection/index.js
  client/src/components/signUpForm/PhysicalCharacteristics/index.js
  client/src/components/userProvider/index.js
  server/__test__/index.test.js
  server/controllers/index.js
  server/controllers/isAuth/index.js
  server/middlewares/errorHandle/index.js
  server/router.js
Labels: Done

#129 fixed axios.get url error
  client/src/components/Home/index.js
Labels: Awaiting Review

#133 Add daily user calories
  client/src/components/CircularProgress/index.js
  client/src/components/Container/index.js
  client/src/components/DailyCaloriesCard/index.js
  client/src/components/DailyUserCalories/index.js
  client/src/components/Home/index.js
  client/src/components/Home/style.js
  client/src/components/Popover/index.js
  client/src/components/food/FoodCategories/index.js
Labels: Done

#126 get exercises back
  server/controllers/getExercise.js
  server/controllers/index.js
  server/database/queries/getExercise.js
  server/database/queries/getUserExercise.js
  server/database/queries/index.js
  server/router.js
Labels: Done

#130 post exercise
  server/controllers/getExercise.js
  server/controllers/index.js
  server/controllers/postExercise.js
  server/database/queries/addExercise.js
  server/database/queries/index.js
  server/router.js
  server/utils/index.js
  server/utils/validation/exerciseValidation.js
  server/utils/validation/index.js
Labels: Done

#135 contact us page
  client/src/App/index.js
  client/src/Pages/ContactUs/index.js
  client/src/Pages/index.js
  client/src/Utils/constant.js
  client/src/components/ContactUs/index.js
  client/src/components/DesktopNavBar/index.js
  client/src/components/DesktopNavBar/style.js
  client/src/components/LoginSignupButtonsBox/index.js
Labels: Done

#136 not found page
  client/src/Pages/NotFoundPage/index.js
  client/src/Pages/index.js
  client/src/components/CircularProgress/index.js
  client/src/components/NotFound/index.js
  client/src/components/NotFound/notfound.png
Labels: Done

#131 Exercises components
  client/package-lock.json
  client/package.json
  client/src/Pages/Exercise/index.js
  client/src/components/CircularProgress/index.js
  client/src/components/Container/index.js
  client/src/components/Popover/index.js
  client/src/components/exercises/AddExercise/index.js
  client/src/components/exercises/AddExercise/style.js
  client/src/components/exercises/ExerciseItem/index.js
  client/src/components/exercises/ExerciseItem/style.js
  client/src/components/exercises/ExerciseItems/index.js
  client/src/components/exercises/ExerciseItems/style.js
  client/src/components/exercises/ExercisesTable/index.js
  client/src/components/exercises/ExercisesTable/style.js
  client/src/components/signUpForm/GenderSelection/index.js
  client/src/components/signUpForm/PhysicalCharacteristics/index.js
  server/controllers/getExercise.js
  server/database/queries/index.js
  server/router.js
Labels: Done

#137 Fix bugs
  client/src/components/DailyUserCalories/index.js
  client/src/components/food/AddFoodQuantityButtons/index.js
  client/src/components/food/FoodCategories/index.js
  client/src/components/food/FoodItemsSelected/index.js
  server/__test__/index.test.js
  server/database/config/fakeData.sql
Labels: Done

#138 Edit Readme
  README.md
Labels: Done
